customhost = "employeeadmin.cqtxnzsulydf.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "bait3273"
customdb = "employee"
custombucket = "laiminghuan-bucket"
customregion = "us-east-1"
